config/routes.rb
Rails.application.routes.draw do
  
  post "static_page/authorize"
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'static_page#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
	    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	      user.provider = auth.provider
	      user.uid = auth.uid
	      user.name = auth.info.name
	      user.oauth_token = auth.credentials.token
	      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	      user.save!
	    end
	end

	def facebook
		@facebook ||= Koala::Facebook::API.new(oauth_token)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
	  def current_user
	    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end
	  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
  end

  def authorize
  	repond_to do |format|
  		format.html
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookApi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  

  <div id="container">
    <div id="user-widget">
      <% if current_user %>
        Welcome <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </div>
      <%= yield %>
    </div>

</body>
</html>

app/views/static_page/authorize.html.erb
<script type="text/javascript">
	top.location.href = "http://locahost:3000/auth/facebook";
</script>

app/views/static_page/index.html.erb
<h1>StaticPage#index</h1>
<p>Find me in app/views/static_page/index.html.erb</p>

<% if current_user %>
	<div id="friends">
		<p> <%= link_to "Invite your Facebook friends", "#", :id => "invite_fb_friends" %> </p> 

		<div id="fb-root"></div>

		<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>

		<script> 
		$(function() { 
			$("a#invite_fb_friends").click(function() { 
			FB.ui({method: 'apprequests', message:'Hey! We need beta testers for this new app. No spam, ' + 'a bit of thinking before posting, and fun with friends.' }); 
			}); 
		}); 
		</script> 
	</div>
<% end %>